# Generated by Django 2.2.5 on 2020-01-08 21:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(default='coleccion', max_length=32)),
                ('tipo', models.CharField(choices=[('Evento', 'Evento'), ('Comunion', 'Comunion'), ('Bautizo', 'Bautizo'), ('Verano', 'Verano')], default='Evento', max_length=32)),
                ('anyo', models.IntegerField(default=2020, max_length=4)),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(default='default.jpg', upload_to='galeria_imagenes')),
                ('coleccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicio.Coleccion')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
