# Generated by Django 2.2.5 on 2020-01-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20200108_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleccion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='coleccion',
            name='nombre_publico',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='nombre_real',
            field=models.CharField(default='', max_length=32),
        ),
    ]
