# Generated by Django 2.2.5 on 2020-01-10 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20200108_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(default='', max_length=32)),
                ('apellidos', models.CharField(default='', max_length=120)),
                ('correo', models.CharField(default='', max_length=120)),
                ('pais', models.CharField(default='', max_length=120)),
                ('prefijo', models.CharField(default='', max_length=120)),
                ('telefono', models.IntegerField(default=0)),
                ('idioma', models.CharField(default='', max_length=120)),
                ('mensaje', models.CharField(default='', max_length=5000)),
            ],
            options={
                'verbose_name': 'Formulario de contacto',
                'verbose_name_plural': 'Formularios de contacto',
            },
        ),
    ]
